### ISSUE TITLE
embedding of srcNodes and tgtNodes

### ISSUE THREAD

**Issue by GhostShipZ** [anonymous0908X/KHGT#1]
Hello, I have a question. In the "messagePropagate" function, why do srcNodes and tgtNodes look up their embeddings in the same embedding table?

**Comment by akaxlh** [comment]
> Hello, I have a question. In the "messagePropagate" function, why do srcNodes and tgtNodes look up their embeddings in the same embedding table?

We didn't intend to do the parameter sharing. Thank you for pointing out the mistake, and the code has been updated.  While the model performance is similar by tests, which may be due to the huge amount and the high sparsity.
