### ISSUE TITLE
embedding of uEmbed0/iEmbed0 and UEmbedPred/IEmbedPred

### ISSUE THREAD

**Issue by fsgdrq** [anonymous0908X/KHGT#2]
Hello I have a question about embedding of uEmbed0/iEmbed0 and UEmbedPred/IEmbedPred.

In "ours" function, why Embed0 is replaced by a random initialized EmbedPred in code line 125~126 in labcode_ml10m.py？I didn't find a description of it in the paper, and I don't understand what the motivation is for doing so.

I am confused. 

Anyway, thanks of the codes. It is pretty.

**Comment by akaxlh** [comment]
This a small trick we find. Sometimes it works better to use new 0-order embeddings. As it is rather minor, we didn't mention it in the paper.
