### ISSUE TITLE
框架安装包版本

### ISSUE THREAD

**Issue by jzhou3700** [anonymous0908X/KHGT#4]
你好，您这个源码里面少放了安装包的版本，使用tensorflow的一些版本来跑程序的时候，一直出错。

**Comment by xiaoyu-18** [comment]
> 你好，您这个源码里面少放了安装包的版本，使用tensorflow的一些版本来跑程序的时候，一直出错。

您好，请问您有复现成功吗？是使用的哪一个版本？

**Comment by git-hawk** [comment]
> 你好，您这个源码里面少放了安装包的版本，使用tensorflow的一些版本来跑程序的时候，一直出错。
请问您用的tensorflow版本是多少

**Comment by 1310374310** [comment]
> > 你好，您这个源码里面少放了安装包的版本，使用tensorflow的一些版本来跑程序的时候，一直出错。
> > 请问您用的tensorflow版本是多少

你好，我成功运行了这个代码，建议python安装3.6版本，tensorflow默认安装即可（我用的tf1.13）,不建议使用超过python3.6的版本。注意tf与python版本的对应即可。代码是用tf1.x写的，如果迁移到tf2.x上需要改一些地方。

**Comment by akaxlh** [comment]
tensorflow版本是1.14，python版本是3.6
