### ISSUE TITLE
Datasets problem

### ISSUE THREAD

**Issue by Weile0409** [anonymous0908X/KHGT#5]
Dear author, I would like to ask you some problems in datasets
that is, the user of each dataset exceed 10000, but I found that only 10000 users in test data
For example, there are 67788 users in ML10M, but only 10000 users are chosen for test, is it reasonable? 
Thanks!

**Comment by akaxlh** [comment]
Hi, we followed related work to use only 10000 users for test, because some of the datasets contain too many users. The test protocol is same for all baselines, so the experimental results are solid.
