### ISSUE TITLE
Issue run retail dataset

### ISSUE THREAD

**Issue by KylinA1** [anonymous0908X/KHGT#7]
Hi, Thank you for your quick response.
I was unable to run the code on retail dataset. (and Successfully run the code on ml10m and yelp datasets )
BTW, I have fixed the following minor issues to enable the correctness:
-  change the folder name from 'Yelp' to 'yelp' (match the folder name in DataHandler_time.py)
-  change line 14 in DataHandler_time.py  to 'retail' (instead of 'Tmall')

During the execution of 
```python
python labcode_retail.py --data retail --graphSampleN 15000 --reg 1e-1 --save_path model_name
```
The error pops out due to the index out of range. I think these are some issues with the dataset.
Please let me know if you could get it run.
And would you mind to sharing me the original data and data preprocessing code?

**Comment by akaxlh** [comment]
Thank you for your bugfix! I'll check the issue as soon as possible.

**Comment by KylinA1** [comment]
> Thank you for your bugfix! I'll check the issue as soon as possible.

Thanks for your response.
I couldn't understand the following steps in line76-78 of `labcode_yelp.py`
```python
		padTgtNodes = tf.concat([tgtNodes, tf.constant([maxNum], dtype=tf.int64)], axis=-1)
		attval = tf.reshape(tf.math.segment_sum(padAttval, padTgtNodes), [-1, args.latdim])
		attval = tf.slice(attval, [0, 0], [maxNum, -1])
```
while in `labcode_ml10m.py` it changes to
```python
		padTgtNodes = tf.concat([tgtNodes, tf.reshape(maxNum-1, [1])], axis=-1)
		attval = tf.reshape(tf.math.segment_sum(padAttval, padTgtNodes), [-1, args.latdim])
```

why we need to padding the target Nodes.

**Comment by akaxlh** [comment]
Hi, sorry for the delay.
1. The padding is to avoid the situation that the row with biggest id is not involved, in which case the result embedding matrix will lose these rows.
2. The error. I don't have the index out of range error here. Do you have this error every time or just sometimes. If this error occurs occassionally, it may relate to the sub-graph sampling algorithm.
3. Dataset and processing code. You can email me at aka_xia@foxmail.com. I will send you the original data and processing code.
4. Thank you for your bugfix.
